project:
  type: website

website:
  title: "Model sculpting examples"
  sidebar:
    contents:
      - index.qmd
      - section: Notebook
        contents: notebook/*
    tools:
      - icon: github
        href: https://github.com/Genentech/modsculpt_example
  repo-url: https://github.com/Genentech/modsculpt_example
  repo-actions: [edit, issue]
  
format:
  html:
    theme: sandstone
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    toc: true
    toc_float: true

date-format: iso

execute:
  freeze: true
